# Generated by Django 4.2 on 2023-04-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=233)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=433)),
                ("rollno", models.IntegerField()),
                ("marks", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeacharsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=233)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=433)),
                ("subject", models.CharField(max_length=233)),
                ("salary", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
