# Generated by Django 4.2 on 2023-04-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modelsapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=233)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=433)),
            ],
        ),
        migrations.CreateModel(
            name="StudentInfo1",
            fields=[
                (
                    "contactinfo1_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="modelsapp.contactinfo1",
                    ),
                ),
                ("rollno", models.IntegerField()),
                ("marks", models.IntegerField()),
            ],
            bases=("modelsapp.contactinfo1",),
        ),
        migrations.CreateModel(
            name="TeacharsInfo1",
            fields=[
                (
                    "contactinfo1_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="modelsapp.contactinfo1",
                    ),
                ),
                ("subject", models.CharField(max_length=233)),
                ("salary", models.BigIntegerField()),
            ],
            bases=("modelsapp.contactinfo1",),
        ),
    ]
